// Every user-facing string, English and Mongolian. The engine returns ids; the shell looks them up here.
// Mongolian copy needs a native speaker's review before publishing (see the spec's Further Notes).

export const STRINGS = {
  en: {
    'tab.play': 'Play',
    'tab.train': 'Train',
    'tab.improve': 'Improve',
    loading: 'Loading…',
    bootFailed: 'Blackjack Lab failed to start. Please reopen it.',

    chips: 'Chips',
    player: 'Player',
    guestName: 'Guest',
    guestNote: 'Log in to rank',
    previewName: 'Preview',
    previewNote: 'Open in Usion to play as you',
    bestShort: 'Best streak {n}',
    keysBet: 'Keys: 1–4 chips · Enter deal · C clear · R rebet · A auto bet',
    keysAct: 'Keys: H hit · S stand · D double · P split',
    keysTrain: 'Keys: H S D P answer · Enter next',
    autoBet: 'Auto',
    autoNeedsBet: 'Place a Bet first, then turn on Auto.',
    autoStopped: 'Auto bet stopped: your Bet no longer fits your chips.',
    cardsLeft: '{n} cards left',
    dealer: 'Dealer',
    feltPays: 'Blackjack pays 3 to 2',
    feltRule: 'Dealer stands on all 17s',
    feltTrain: 'What would the Book do?',
    feltTrainSub: 'Basic strategy drill',
    bet: 'Bet',
    clear: 'Clear',
    rebet: 'Rebet',
    deal: 'Deal',
    hint: 'Hint',
    hintSays: 'Hint: {action}',
    softTotal: 'Soft {n}',
    'action.hit': 'Hit',
    'action.stand': 'Stand',
    'action.double': 'Double',
    'action.split': 'Split',
    'result.blackjack': 'Blackjack',
    'result.win': 'Win',
    'result.push': 'Push',
    'result.lose': 'Lose',
    'result.bust': 'Bust',
    roundNet: 'Round {n}',
    coachMistake: 'Book: {action}',
    refilled: 'Out of chips — refilled to {n}.',

    'drill.weighted': 'Drill',
    'drill.mistakes': 'My mistakes',
    streak: 'Streak',
    best: 'Best',
    yourHand: 'Your hand',
    correct: 'Correct',
    next: 'Next',
    emptyTitle: 'No mistakes to practise.',
    emptyBody: 'Cells you get wrong land here until you get them right twice in a row.',
    backToDrill: 'Back to the drill',
    'drill.values': 'Values',
    time: 'Time',
    bestSprint: 'Best sprint',
    start: 'Start',
    again: 'Again',
    feltValues: 'Values sprint · 30 s',
    feltValuesSub: '+1 for 2–6 · 0 for 7–9 · −1 for 10–A',
    sprintResult: '{score} right · {misses} missed',
    sprintNewBest: 'New best sprint!',
    sprintBestWas: 'Best sprint: {n}',
    sprintMiss: 'Missed: it was {value}',
    keysValues: 'Keys: ← −1 · ↓ 0 · → +1 (or 1 2 3) · Enter start',
    'drill.count': 'Count',
    checks: 'Checks',
    'speed.slow': 'Slow',
    'speed.normal': 'Normal',
    'speed.fast': 'Fast',
    feltCount: 'Keep the count',
    feltCountSub: 'Hi-Lo · +1 for 2–6 · 0 for 7–9 · −1 for 10–A',
    newShoe: 'New Shoe',
    newShoeSub: 'The count starts at 0',
    'ask.runningCount': 'Running count?',
    'askSub.runningCount': 'Every card since the shuffle',
    'ask.trueCount': 'True count?',
    'askSub.trueCount': 'Running count ÷ decks left (read the tray)',
    'ask.bet': 'Bet (units)?',
    'askSub.bet': 'True count − 1, from 1 to 8 units',
    'label.runningCount': 'Running count',
    'label.trueCount': 'True count',
    'label.bet': 'Bet size',
    itWas: '{what} was {n}',
    youSaid: 'You said {n}',
    carryOn: 'Keep counting from here',
    tcWorking: '{rc} ÷ {decks} decks = {exact} → {tc}',
    betWorking: 'True count {tc} → {units}: true count − 1, from 1 to 8',
    betUnit: '{n} unit',
    betUnits: '{n} units',
    oneLess: 'One less',
    oneMore: 'One more',
    answerOk: 'OK',
    trayLabel: 'Discard tray: {n} decks dealt',
    keysCount: 'Keys: 1 2 3 speed · ← → adjust · digits and − type · Enter answer · 1–8 Bet',
    rulesButton: 'Rules',
    chartButton: 'Chart',
    whyHow: 'Why & how',
    lookedUp: "Looked up: this hand isn't counted",
    notCounted: 'not counted',

    accuracy: 'Accuracy',
    'group.hard': 'Hard',
    'group.soft': 'Soft',
    'group.pairs': 'Pairs',
    ofDecisions: '{correct} of {total} correct',
    noStats: 'Play or train to see your stats.',
    chartTitle: 'Your strategy chart',
    chartNote: 'Each cell shows the Book move in its colour. Cells you have not played yet are faded.',
    chartNew: 'Not played yet',
    chartRing: 'Your mistakes (thicker ring = more often)',
    chartCell: '{row} vs {up}: {action}. {correct} of {total} correct.',
    chartCellEmpty: '{row} vs {up}: {action}. Not played yet.',
    chartCellPlain: '{row} vs {up}: {action}.',
    mistakesTitle: 'Recent mistakes',
    noMistakes: 'No mistakes yet.',
    mistakeLine: 'You: {chosen} · Book: {book}',
    versus: 'vs',
    'source.play': 'Play',
    'source.weighted': 'Drill',
    'source.mistakes': 'My mistakes',
    tableTitle: 'Table results',
    hands: 'Hands',
    wins: 'Wins',
    losses: 'Losses',
    pushes: 'Pushes',
    net: 'Net chips',
    resetStats: 'Reset stats',
    newBankroll: 'New bankroll',
    bankrollTitleFirst: 'How many chips do you want to start with?',
    bankrollBody: 'When you run out, a Refill tops you back up to this amount.',
    bankrollConfirm: 'Replace your {current} chips with {n}?',
    bankrollStart: 'Start with {n}',
    bankrollSet: 'Chips set to {n}.',
    finishRoundFirst: 'Finish the Round first.',
    resetConfirm: 'Reset your accuracy, mistakes, table results and counting accuracy? Chips, streaks and your best sprint stay.',
    countingTitle: 'Card counting',
    countValues: 'Count values',
    sprintUnit: 'cards in 30 s',
    reset: 'Reset',
    cancel: 'Cancel',
    close: 'Close',
    tourSkip: 'Skip',
    tourBack: 'Back',
    tourChips: 'Choose your chips',
    tourDone: 'Done',
    tourReplay: 'Replay the tour',
    tourStep: 'Slide {n} of {total}',
    guide: 'Guide',
    guideOpen: 'Open the Guide',

    boardTitle: 'Leaderboard · best streak',
    friends: 'Friends',
    global: 'Global',
    yourRank: 'Your rank: #{rank} of {total}',
    loginToRank: 'Log in to rank your best streak.',
    boardLoading: 'Loading leaderboard…',
    boardError: "Couldn't load the leaderboard.",
    boardEmpty: 'No records yet.',
    boardPreview: 'The leaderboard is available inside Usion.',
    newBestTitle: 'New best streak!',
    newBestBody: '{n} correct in a row.',
    newBestRank: 'You are #{rank}.',

    saveFailed: 'Progress not saved — will retry.',
    loadFailed: "Couldn't load your progress. This session won't be saved.",
    preview: 'Preview mode — progress is not saved.',

    'rank.A': 'Ace',
    'rank.K': 'King',
    'rank.Q': 'Queen',
    'rank.J': 'Jack',
    'suit.s': 'spades',
    'suit.h': 'hearts',
    'suit.d': 'diamonds',
    'suit.c': 'clubs',
    cardOf: '{rank} of {suit}',
    faceDown: 'Face-down card',

    'rule.aces-eights': 'Always split aces and eights.',
    'rule.never-tens': 'Never split tens — 20 is too strong to break.',
    'rule.never-fives': 'Never split fives — play them as a hard 10: double against 2–9.',
    'rule.small-pairs': 'Split 2s, 3s and 7s against 2–7; hit against 8 or higher.',
    'rule.sixes': 'Split 6s against 2–6; hit against 7 or higher.',
    'rule.fours': 'Split 4s only against 5 or 6; otherwise hit.',
    'rule.nines': 'Split 9s against 2–9 except 7; stand against 7, 10 and ace.',
    'rule.hard-8': 'Always hit 8 or less.',
    'rule.hard-9': 'Double 9 against 3–6; otherwise hit.',
    'rule.hard-10': 'Double 10 against 2–9; hit against 10 or ace.',
    'rule.hard-11': 'Double 11 against 2–10; hit against an ace.',
    'rule.hard-12': 'Stand on 12 against 4–6; hit against 2, 3 and 7 or higher.',
    'rule.stiff': 'Stand on 13–16 against 2–6; hit against 7 or higher.',
    'rule.hard-17': 'Always stand on hard 17 or more.',
    'rule.soft-double':
      'Double soft hands against weak dealer cards (A2–A3 vs 5–6, A4–A5 vs 4–6, A6 vs 3–6); otherwise hit.',
    'rule.soft-18': 'Soft 18: double against 3–6, stand against 2, 7 and 8, hit against 9, 10 and ace.',
    'rule.soft-19': 'Always stand on soft 19 or more.',
    'rule.no-double': "Can't double here? Hit instead — but stand on soft 18.",
    'rule.no-split': "Can't split? Play the pair as its total.",
  },

  mn: {
    'tab.play': 'Тоглох',
    'tab.train': 'Дасгал',
    'tab.improve': 'Ахиц',
    loading: 'Ачаалж байна…',
    bootFailed: 'Blackjack Lab эхэлж чадсангүй. Дахин нээнэ үү.',

    chips: 'Жетон',
    player: 'Тоглогч',
    guestName: 'Зочин',
    guestNote: 'Нэвтэрч эрэмбэд ор',
    previewName: 'Урьдчилан харах',
    previewNote: 'Өөрийн нэрээр тоглохын тулд Usion-д нээнэ үү',
    bestShort: 'Шилдэг цуврал {n}',
    keysBet: 'Товч: 1–4 жетон · Enter тараах · C арилгах · R дахин · A авто',
    keysAct: 'Товч: H авах · S зогсох · D давхарлах · P хуваах',
    keysTrain: 'Товч: H S D P хариулах · Enter дараах',
    autoBet: 'Авто',
    autoNeedsBet: 'Эхлээд бооцоо тавиад Авто-г асаана уу.',
    autoStopped: 'Авто бооцоо зогслоо: бооцоо тань жетонд багтахгүй байна.',
    cardsLeft: '{n} карт үлдсэн',
    dealer: 'Дилер',
    feltPays: 'Блэкжек 3:2 төлнө',
    feltRule: 'Дилер бүх 17 дээр зогсоно',
    feltTrain: 'Стратеги юу гэж хэлэх вэ?',
    feltTrainSub: 'Үндсэн стратегийн дасгал',
    bet: 'Бооцоо',
    clear: 'Арилгах',
    rebet: 'Дахин',
    deal: 'Тараах',
    hint: 'Зөвлөгөө',
    hintSays: 'Зөвлөгөө: {action}',
    softTotal: 'Зөөлөн {n}',
    'action.hit': 'Авах',
    'action.stand': 'Зогсох',
    'action.double': 'Давхарлах',
    'action.split': 'Хуваах',
    'result.blackjack': 'Блэкжек',
    'result.win': 'Хожсон',
    'result.push': 'Тэнцсэн',
    'result.lose': 'Хожигдсон',
    'result.bust': 'Хэтэрсэн',
    roundNet: 'Тойрог {n}',
    coachMistake: 'Стратеги: {action}',
    refilled: 'Жетон дууссан — {n} болгож нөхлөө.',

    'drill.weighted': 'Дасгал',
    'drill.mistakes': 'Миний алдаа',
    streak: 'Цуврал',
    best: 'Шилдэг',
    yourHand: 'Таны гар',
    correct: 'Зөв',
    next: 'Дараах',
    emptyTitle: 'Давтах алдаа алга.',
    emptyBody: 'Буруу хариулсан нүд тань хоёр удаа дараалан зөв хариулах хүртэл энд гарна.',
    backToDrill: 'Дасгал руу буцах',
    'drill.values': 'Утга',
    time: 'Хугацаа',
    bestSprint: 'Шилдэг спринт',
    start: 'Эхлэх',
    again: 'Дахин',
    feltValues: 'Утгын спринт · 30 с',
    feltValuesSub: '2–6: +1 · 7–9: 0 · 10–A: −1',
    sprintResult: '{score} зөв · {misses} алдсан',
    sprintNewBest: 'Шинэ шилдэг спринт!',
    sprintBestWas: 'Шилдэг спринт: {n}',
    sprintMiss: 'Алдлаа: {value} байсан',
    keysValues: 'Товч: ← −1 · ↓ 0 · → +1 (эсвэл 1 2 3) · Enter эхлэх',
    'drill.count': 'Тоолох',
    checks: 'Шалгалт',
    'speed.slow': 'Удаан',
    'speed.normal': 'Дунд',
    'speed.fast': 'Хурдан',
    feltCount: 'Тоогоо барь',
    feltCountSub: 'Hi-Lo · 2–6: +1 · 7–9: 0 · 10–A: −1',
    newShoe: 'Шинэ хайрцаг',
    newShoeSub: 'Тоолол 0-ээс эхэлнэ',
    'ask.runningCount': 'Явцын тоо?',
    'askSub.runningCount': 'Холисноос хойшхи бүх карт',
    'ask.trueCount': 'Жинхэнэ тоо?',
    'askSub.trueCount': 'Явцын тоо ÷ үлдсэн багц (тавиурыг хар)',
    'ask.bet': 'Бооцоо (нэгж)?',
    'askSub.bet': 'Жинхэнэ тоо − 1, 1-ээс 8 нэгж',
    'label.runningCount': 'Явцын тоо',
    'label.trueCount': 'Жинхэнэ тоо',
    'label.bet': 'Бооцооны хэмжээ',
    itWas: '{what}: {n} байсан',
    youSaid: 'Та {n} гэж хэлсэн',
    carryOn: 'Эндээс үргэлжлүүлэн тоол',
    tcWorking: '{rc} ÷ {decks} багц = {exact} → {tc}',
    betWorking: 'Жинхэнэ тоо {tc} → {units}: жинхэнэ тоо − 1, 1-ээс 8',
    betUnit: '{n} нэгж',
    betUnits: '{n} нэгж',
    oneLess: 'Нэгээр бага',
    oneMore: 'Нэгээр их',
    answerOk: 'OK',
    trayLabel: 'Хаягдлын тавиур: {n} багц тараагдсан',
    keysCount: 'Товч: 1 2 3 хурд · ← → өөрчлөх · тоо ба − бичих · Enter хариулах · 1–8 бооцоо',
    rulesButton: 'Дүрэм',
    chartButton: 'Хүснэгт',
    whyHow: 'Яагаад, яаж',
    lookedUp: 'Хүснэгт харсан: энэ гар тоологдохгүй',
    notCounted: 'тоологдохгүй',

    accuracy: 'Нарийвчлал',
    'group.hard': 'Хатуу',
    'group.soft': 'Зөөлөн',
    'group.pairs': 'Хос',
    ofDecisions: '{total}-с {correct} зөв',
    noStats: 'Статистик харахын тулд тоглох эсвэл дасгал хийнэ үү.',
    chartTitle: 'Таны стратегийн хүснэгт',
    chartNote: 'Нүд бүр стратегийн шийдвэрийг өнгөөр харуулна. Тоглоогүй нүд бүдэг байна.',
    chartNew: 'Одоогоор тоглоогүй',
    chartRing: 'Таны алдаа (зузаан хүрээ = олон удаа)',
    chartCell: '{row} ба {up}: {action}. {total}-с {correct} зөв.',
    chartCellEmpty: '{row} ба {up}: {action}. Одоогоор тоглоогүй.',
    chartCellPlain: '{row} ба {up}: {action}.',
    mistakesTitle: 'Сүүлийн алдаанууд',
    noMistakes: 'Алдаа алга байна.',
    mistakeLine: 'Та: {chosen} · Стратеги: {book}',
    versus: 'эсрэг',
    'source.play': 'Тоглолт',
    'source.weighted': 'Дасгал',
    'source.mistakes': 'Миний алдаа',
    tableTitle: 'Ширээний үр дүн',
    hands: 'Гар',
    wins: 'Хожил',
    losses: 'Хожигдол',
    pushes: 'Тэнцээ',
    net: 'Цэвэр жетон',
    resetStats: 'Статистик арилгах',
    newBankroll: 'Шинэ жетон',
    bankrollTitleFirst: 'Хэдэн жетоноор эхлэх вэ?',
    bankrollBody: 'Жетон дуусахад энэ хэмжээ хүртэл нөхөгдөнө.',
    bankrollConfirm: 'Одоогийн {current} жетоныг {n}-оор солих уу?',
    bankrollStart: '{n}-оор эхлэх',
    bankrollSet: 'Жетон {n} боллоо.',
    finishRoundFirst: 'Эхлээд тойргоо дуусгана уу.',
    resetConfirm: 'Нарийвчлал, алдаа, ширээний үр дүн, тоолох нарийвчлалыг арилгах уу? Жетон, цуврал, шилдэг спринт хэвээр үлдэнэ.',
    countingTitle: 'Карт тоолох',
    countValues: 'Картын утга',
    sprintUnit: '30 секундэд',
    reset: 'Арилгах',
    cancel: 'Болих',
    close: 'Хаах',
    tourSkip: 'Алгасах',
    tourBack: 'Буцах',
    tourChips: 'Жетоноо сонгох',
    tourDone: 'Болсон',
    tourReplay: 'Танилцуулгыг дахин үзэх',
    tourStep: '{total}-с {n}-р хуудас',
    guide: 'Гарын авлага',
    guideOpen: 'Гарын авлага нээх',

    boardTitle: 'Тэргүүлэгчид · шилдэг цуврал',
    friends: 'Найзууд',
    global: 'Дэлхий',
    yourRank: 'Таны байр: {total}-с #{rank}',
    loginToRank: 'Шилдэг цувралаа эрэмбэд оруулахын тулд нэвтэрнэ үү.',
    boardLoading: 'Тэргүүлэгчдийг ачаалж байна…',
    boardError: 'Тэргүүлэгчдийг ачаалж чадсангүй.',
    boardEmpty: 'Одоогоор рекорд алга.',
    boardPreview: 'Тэргүүлэгчид зөвхөн Usion дотор харагдана.',
    newBestTitle: 'Шинэ шилдэг цуврал!',
    newBestBody: 'Дараалан {n} зөв.',
    newBestRank: 'Та #{rank}-т байна.',

    saveFailed: 'Ахиц хадгалагдсангүй — дахин оролдоно.',
    loadFailed: 'Таны ахицыг ачаалж чадсангүй. Энэ удаагийн тоглолт хадгалагдахгүй.',
    preview: 'Урьдчилан харах горим — ахиц хадгалагдахгүй.',

    'rank.A': 'Тамга',
    'rank.K': 'Хаан',
    'rank.Q': 'Хатан',
    'rank.J': 'Боол',
    'suit.s': 'гил',
    'suit.h': 'зүрх',
    'suit.d': 'дөрвөлжин',
    'suit.c': 'цэцэг',
    cardOf: '{suit} {rank}',
    faceDown: 'Нүүрээрээ доош харсан карт',

    'rule.aces-eights': 'Тамга болон наймыг үргэлж хуваа.',
    'rule.never-tens': 'Аравтыг хэзээ ч бүү хуваа — 20 хэтэрхий хүчтэй.',
    'rule.never-fives': 'Тавыг бүү хуваа — хатуу 10 гэж тоглоод 2–9-ийн эсрэг давхарла.',
    'rule.small-pairs': '2, 3, 7-г 2–7-ийн эсрэг хуваа; 8 ба түүнээс дээшийн эсрэг ав.',
    'rule.sixes': '6-г 2–6-ийн эсрэг хуваа; 7 ба түүнээс дээшийн эсрэг ав.',
    'rule.fours': '4-г зөвхөн 5 эсвэл 6-ын эсрэг хуваа; бусад үед ав.',
    'rule.nines': '9-ийг 7-гоос бусад 2–9-ийн эсрэг хуваа; 7, 10, тамганы эсрэг зогс.',
    'rule.hard-8': '8 ба түүнээс бага бол үргэлж ав.',
    'rule.hard-9': '9-ийг 3–6-ийн эсрэг давхарла; бусад үед ав.',
    'rule.hard-10': '10-ыг 2–9-ийн эсрэг давхарла; 10 эсвэл тамганы эсрэг ав.',
    'rule.hard-11': '11-ийг 2–10-ын эсрэг давхарла; тамганы эсрэг ав.',
    'rule.hard-12': '12 дээр 4–6-ийн эсрэг зогс; 2, 3 болон 7-оос дээшийн эсрэг ав.',
    'rule.stiff': '13–16 дээр 2–6-ийн эсрэг зогс; 7 ба түүнээс дээшийн эсрэг ав.',
    'rule.hard-17': 'Хатуу 17 ба түүнээс дээш бол үргэлж зогс.',
    'rule.soft-double':
      'Зөөлөн гарыг дилерийн сул картын эсрэг давхарла (A2–A3: 5–6, A4–A5: 4–6, A6: 3–6); бусад үед ав.',
    'rule.soft-18': 'Зөөлөн 18: 3–6-ийн эсрэг давхарла, 2, 7, 8-ын эсрэг зогс, 9, 10, тамганы эсрэг ав.',
    'rule.soft-19': 'Зөөлөн 19 ба түүнээс дээш бол үргэлж зогс.',
    'rule.no-double': 'Давхарлах боломжгүй юу? Оронд нь ав — харин зөөлөн 18 дээр зогс.',
    'rule.no-split': 'Хуваах боломжгүй юу? Хосыг нийлбэрээр нь тогло.',
  },
}
