// Every user-facing string, English and Mongolian. The engine returns ids; the shell looks them up here.
// Mongolian copy needs a native speaker's review before publishing (see the spec's Further Notes).

export const STRINGS = {
  en: {
    'tab.play': 'Play',
    'tab.train': 'Train',
    'tab.improve': 'Improve',
    loading: 'Loading…',
    bootFailed: 'Blackjack Lab failed to start. Please reopen it.',

    chips: 'Chips',
    player: 'Player',
    guestName: 'Guest',
    guestNote: 'Log in to rank',
    previewName: 'Preview',
    previewNote: 'Open in Usion to play as you',
    bestShort: 'Best streak {n}',
    keysBet: 'Keys: 1–4 chips · Enter deal · C clear · R rebet · A auto bet',
    keysAct: 'Keys: H hit · S stand · D double · P split',
    keysTrain: 'Keys: H S D P answer · Enter next',
    autoBet: 'Auto',
    autoStopped: 'Auto bet stopped: your Bet no longer fits your chips.',
    cardsLeft: '{n} cards left',
    dealer: 'Dealer',
    feltPays: 'Blackjack pays 3 to 2',
    feltRule: 'Dealer stands on all 17s',
    feltTrain: 'What would the Book do?',
    feltTrainSub: 'Basic strategy drill',
    bet: 'Bet',
    clear: 'Clear',
    rebet: 'Rebet',
    deal: 'Deal',
    hint: 'Hint',
    hintSays: 'Hint: {action}',
    softTotal: 'Soft {n}',
    'action.hit': 'Hit',
    'action.stand': 'Stand',
    'action.double': 'Double',
    'action.split': 'Split',
    'result.blackjack': 'Blackjack',
    'result.win': 'Win',
    'result.push': 'Push',
    'result.lose': 'Lose',
    'result.bust': 'Bust',
    roundNet: 'Round {n}',
    coachMistake: 'Book: {action}',
    refilled: 'Out of chips — refilled to {n}.',

    'drill.weighted': 'Drill',
    'drill.mistakes': 'My mistakes',
    streak: 'Streak',
    best: 'Best',
    yourHand: 'Your hand',
    correct: 'Correct',
    next: 'Next',
    emptyTitle: 'No mistakes to practise.',
    emptyBody: 'Cells you get wrong land here until you get them right twice in a row.',
    backToDrill: 'Back to the drill',

    accuracy: 'Accuracy',
    'group.hard': 'Hard',
    'group.soft': 'Soft',
    'group.pairs': 'Pairs',
    ofDecisions: '{correct} of {total} correct',
    noStats: 'Play or train to see your stats.',
    chartTitle: 'Your strategy chart',
    chartNote: 'Letters are the Book. Darker cells are where you make more mistakes.',
    chartNoData: 'Not played',
    chartScale: 'Mistake rate',
    chartCell: '{row} vs {up}: {action}. {correct} of {total} correct.',
    chartCellEmpty: '{row} vs {up}: {action}. Not played yet.',
    mistakesTitle: 'Recent mistakes',
    noMistakes: 'No mistakes yet.',
    mistakeLine: 'You: {chosen} · Book: {book}',
    versus: 'vs',
    'source.play': 'Play',
    'source.weighted': 'Drill',
    'source.mistakes': 'My mistakes',
    tableTitle: 'Table results',
    hands: 'Hands',
    wins: 'Wins',
    losses: 'Losses',
    pushes: 'Pushes',
    net: 'Net chips',
    resetStats: 'Reset stats',
    resetConfirm: 'Reset your accuracy, mistakes and table results? Chips and streaks stay.',
    reset: 'Reset',
    cancel: 'Cancel',
    close: 'Close',

    boardTitle: 'Leaderboard · best streak',
    friends: 'Friends',
    global: 'Global',
    yourRank: 'Your rank: #{rank} of {total}',
    loginToRank: 'Log in to rank your best streak.',
    boardLoading: 'Loading leaderboard…',
    boardError: "Couldn't load the leaderboard.",
    boardEmpty: 'No records yet.',
    boardPreview: 'The leaderboard is available inside Usion.',
    newBestTitle: 'New best streak!',
    newBestBody: '{n} correct in a row.',
    newBestRank: 'You are #{rank}.',

    saveFailed: 'Progress not saved — will retry.',
    loadFailed: "Couldn't load your progress. This session won't be saved.",
    preview: 'Preview mode — progress is not saved.',

    'rank.A': 'Ace',
    'rank.K': 'King',
    'rank.Q': 'Queen',
    'rank.J': 'Jack',
    'suit.s': 'spades',
    'suit.h': 'hearts',
    'suit.d': 'diamonds',
    'suit.c': 'clubs',
    cardOf: '{rank} of {suit}',
    faceDown: 'Face-down card',

    'rule.aces-eights': 'Always split aces and eights.',
    'rule.never-tens': 'Never split tens — 20 is too strong to break.',
    'rule.never-fives': 'Never split fives — play them as a hard 10: double against 2–9.',
    'rule.small-pairs': 'Split 2s, 3s and 7s against 2–7; hit against 8 or higher.',
    'rule.sixes': 'Split 6s against 2–6; hit against 7 or higher.',
    'rule.fours': 'Split 4s only against 5 or 6; otherwise hit.',
    'rule.nines': 'Split 9s against 2–9 except 7; stand against 7, 10 and ace.',
    'rule.hard-8': 'Always hit 8 or less.',
    'rule.hard-9': 'Double 9 against 3–6; otherwise hit.',
    'rule.hard-10': 'Double 10 against 2–9; hit against 10 or ace.',
    'rule.hard-11': 'Double 11 against 2–10; hit against an ace.',
    'rule.hard-12': 'Stand on 12 against 4–6; hit against 2, 3 and 7 or higher.',
    'rule.stiff': 'Stand on 13–16 against 2–6; hit against 7 or higher.',
    'rule.hard-17': 'Always stand on hard 17 or more.',
    'rule.soft-double':
      'Double soft hands against weak dealer cards (A2–A3 vs 5–6, A4–A5 vs 4–6, A6 vs 3–6); otherwise hit.',
    'rule.soft-18': 'Soft 18: double against 3–6, stand against 2, 7 and 8, hit against 9, 10 and ace.',
    'rule.soft-19': 'Always stand on soft 19 or more.',
    'rule.no-double': "Can't double here? Hit instead — but stand on soft 18.",
    'rule.no-split': "Can't split? Play the pair as its total.",
  },

  mn: {
    'tab.play': 'Тоглох',
    'tab.train': 'Дасгал',
    'tab.improve': 'Ахиц',
    loading: 'Ачаалж байна…',
    bootFailed: 'Blackjack Lab эхэлж чадсангүй. Дахин нээнэ үү.',

    chips: 'Жетон',
    player: 'Тоглогч',
    guestName: 'Зочин',
    guestNote: 'Нэвтэрч эрэмбэд ор',
    previewName: 'Урьдчилан харах',
    previewNote: 'Өөрийн нэрээр тоглохын тулд Usion-д нээнэ үү',
    bestShort: 'Шилдэг цуврал {n}',
    keysBet: 'Товч: 1–4 жетон · Enter тараах · C арилгах · R дахин · A авто',
    keysAct: 'Товч: H авах · S зогсох · D давхарлах · P хуваах',
    keysTrain: 'Товч: H S D P хариулах · Enter дараах',
    autoBet: 'Авто',
    autoStopped: 'Авто бооцоо зогслоо: бооцоо тань жетонд багтахгүй байна.',
    cardsLeft: '{n} карт үлдсэн',
    dealer: 'Дилер',
    feltPays: 'Блэкжек 3:2 төлнө',
    feltRule: 'Дилер бүх 17 дээр зогсоно',
    feltTrain: 'Стратеги юу гэж хэлэх вэ?',
    feltTrainSub: 'Үндсэн стратегийн дасгал',
    bet: 'Бооцоо',
    clear: 'Арилгах',
    rebet: 'Дахин',
    deal: 'Тараах',
    hint: 'Зөвлөгөө',
    hintSays: 'Зөвлөгөө: {action}',
    softTotal: 'Зөөлөн {n}',
    'action.hit': 'Авах',
    'action.stand': 'Зогсох',
    'action.double': 'Давхарлах',
    'action.split': 'Хуваах',
    'result.blackjack': 'Блэкжек',
    'result.win': 'Хожсон',
    'result.push': 'Тэнцсэн',
    'result.lose': 'Хожигдсон',
    'result.bust': 'Хэтэрсэн',
    roundNet: 'Тойрог {n}',
    coachMistake: 'Стратеги: {action}',
    refilled: 'Жетон дууссан — {n} болгож нөхлөө.',

    'drill.weighted': 'Дасгал',
    'drill.mistakes': 'Миний алдаа',
    streak: 'Цуврал',
    best: 'Шилдэг',
    yourHand: 'Таны гар',
    correct: 'Зөв',
    next: 'Дараах',
    emptyTitle: 'Давтах алдаа алга.',
    emptyBody: 'Буруу хариулсан нүд тань хоёр удаа дараалан зөв хариулах хүртэл энд гарна.',
    backToDrill: 'Дасгал руу буцах',

    accuracy: 'Нарийвчлал',
    'group.hard': 'Хатуу',
    'group.soft': 'Зөөлөн',
    'group.pairs': 'Хос',
    ofDecisions: '{total}-с {correct} зөв',
    noStats: 'Статистик харахын тулд тоглох эсвэл дасгал хийнэ үү.',
    chartTitle: 'Таны стратегийн хүснэгт',
    chartNote: 'Үсэг нь стратегийн шийдвэр. Бараан нүд нь таны олон алддаг газар.',
    chartNoData: 'Тоглоогүй',
    chartScale: 'Алдааны хувь',
    chartCell: '{row} ба {up}: {action}. {total}-с {correct} зөв.',
    chartCellEmpty: '{row} ба {up}: {action}. Одоогоор тоглоогүй.',
    mistakesTitle: 'Сүүлийн алдаанууд',
    noMistakes: 'Алдаа алга байна.',
    mistakeLine: 'Та: {chosen} · Стратеги: {book}',
    versus: 'эсрэг',
    'source.play': 'Тоглолт',
    'source.weighted': 'Дасгал',
    'source.mistakes': 'Миний алдаа',
    tableTitle: 'Ширээний үр дүн',
    hands: 'Гар',
    wins: 'Хожил',
    losses: 'Хожигдол',
    pushes: 'Тэнцээ',
    net: 'Цэвэр жетон',
    resetStats: 'Статистик арилгах',
    resetConfirm: 'Нарийвчлал, алдаа, ширээний үр дүнг арилгах уу? Жетон болон цуврал хэвээр үлдэнэ.',
    reset: 'Арилгах',
    cancel: 'Болих',
    close: 'Хаах',

    boardTitle: 'Тэргүүлэгчид · шилдэг цуврал',
    friends: 'Найзууд',
    global: 'Дэлхий',
    yourRank: 'Таны байр: {total}-с #{rank}',
    loginToRank: 'Шилдэг цувралаа эрэмбэд оруулахын тулд нэвтэрнэ үү.',
    boardLoading: 'Тэргүүлэгчдийг ачаалж байна…',
    boardError: 'Тэргүүлэгчдийг ачаалж чадсангүй.',
    boardEmpty: 'Одоогоор рекорд алга.',
    boardPreview: 'Тэргүүлэгчид зөвхөн Usion дотор харагдана.',
    newBestTitle: 'Шинэ шилдэг цуврал!',
    newBestBody: 'Дараалан {n} зөв.',
    newBestRank: 'Та #{rank}-т байна.',

    saveFailed: 'Ахиц хадгалагдсангүй — дахин оролдоно.',
    loadFailed: 'Таны ахицыг ачаалж чадсангүй. Энэ удаагийн тоглолт хадгалагдахгүй.',
    preview: 'Урьдчилан харах горим — ахиц хадгалагдахгүй.',

    'rank.A': 'Тамга',
    'rank.K': 'Хаан',
    'rank.Q': 'Хатан',
    'rank.J': 'Боол',
    'suit.s': 'гил',
    'suit.h': 'зүрх',
    'suit.d': 'дөрвөлжин',
    'suit.c': 'цэцэг',
    cardOf: '{suit} {rank}',
    faceDown: 'Нүүрээрээ доош харсан карт',

    'rule.aces-eights': 'Тамга болон наймыг үргэлж хуваа.',
    'rule.never-tens': 'Аравтыг хэзээ ч бүү хуваа — 20 хэтэрхий хүчтэй.',
    'rule.never-fives': 'Тавыг бүү хуваа — хатуу 10 гэж тоглоод 2–9-ийн эсрэг давхарла.',
    'rule.small-pairs': '2, 3, 7-г 2–7-ийн эсрэг хуваа; 8 ба түүнээс дээшийн эсрэг ав.',
    'rule.sixes': '6-г 2–6-ийн эсрэг хуваа; 7 ба түүнээс дээшийн эсрэг ав.',
    'rule.fours': '4-г зөвхөн 5 эсвэл 6-ын эсрэг хуваа; бусад үед ав.',
    'rule.nines': '9-ийг 7-гоос бусад 2–9-ийн эсрэг хуваа; 7, 10, тамганы эсрэг зогс.',
    'rule.hard-8': '8 ба түүнээс бага бол үргэлж ав.',
    'rule.hard-9': '9-ийг 3–6-ийн эсрэг давхарла; бусад үед ав.',
    'rule.hard-10': '10-ыг 2–9-ийн эсрэг давхарла; 10 эсвэл тамганы эсрэг ав.',
    'rule.hard-11': '11-ийг 2–10-ын эсрэг давхарла; тамганы эсрэг ав.',
    'rule.hard-12': '12 дээр 4–6-ийн эсрэг зогс; 2, 3 болон 7-оос дээшийн эсрэг ав.',
    'rule.stiff': '13–16 дээр 2–6-ийн эсрэг зогс; 7 ба түүнээс дээшийн эсрэг ав.',
    'rule.hard-17': 'Хатуу 17 ба түүнээс дээш бол үргэлж зогс.',
    'rule.soft-double':
      'Зөөлөн гарыг дилерийн сул картын эсрэг давхарла (A2–A3: 5–6, A4–A5: 4–6, A6: 3–6); бусад үед ав.',
    'rule.soft-18': 'Зөөлөн 18: 3–6-ийн эсрэг давхарла, 2, 7, 8-ын эсрэг зогс, 9, 10, тамганы эсрэг ав.',
    'rule.soft-19': 'Зөөлөн 19 ба түүнээс дээш бол үргэлж зогс.',
    'rule.no-double': 'Давхарлах боломжгүй юу? Оронд нь ав — харин зөөлөн 18 дээр зогс.',
    'rule.no-split': 'Хуваах боломжгүй юу? Хосыг нийлбэрээр нь тогло.',
  },
}
